### ISSUE TITLE
Redirects

### ISSUE THREAD

**Issue by Twista** [Ctvrtkon/ctvrtkon.cz#1]
https://www.netlify.com/docs/redirects/

**Comment by Twista** [comment]
did redirect for the old general links - you can just add some on the end of the file :)
https://github.com/Ctvrtkon/ctvrtkon.cz/blob/master/static/_redirects

**Comment by hlavacm** [comment]
Old links added to _redirects in [#74f7428](https://github.com/Ctvrtkon/ctvrtkon.cz/commit/74f7428771a31b35f7525b92b6d9726f8a2cfd94)
